/* Defter-i Neşeli tasarım notu: Ana defter, tüm kampüsün kapak sayfasıdır; kısa, sakin ve diğer çalışma yapraklarına yönlendiricidir. */
import { ArrowRight, BookMarked, ClipboardCheck, Files, Gamepad2, MapPinned, PlayCircle, Scale, Sparkles, Trophy } from "lucide-react";
import { Link } from "wouter";
import { ASSETS } from "@/data/learningData";
import { StudyLayout } from "@/components/StudyLayout";

const destinations = [{ href: "/temel-kavramlar", icon: Sparkles, label: "Temel Kavramlar", text: "Varlık, borç, tahakkuk ve dönemsellik önce burada netleşir." }, { href: "/oyunlar", icon: Gamepad2, label: "Oyunlar", text: "Yevmiye fişi, koşu turu ve eşleştirmeyle pratik yap." }, { href: "/hesap-rotasi", icon: MapPinned, label: "Hesap Rotası", text: "Belgeden bakiyeye altı farklı işlem zincirini izle." }, { href: "/sinav-merkezi", icon: ClipboardCheck, label: "Sınav Merkezi", text: "Haftalık planı ve konu atlasını aç." }, { href: "/video-dersleri", icon: PlayCircle, label: "Video Dersleri", text: "2026 çözüm videolarını ders ve konuya göre filtrele." }, { href: "/pdf-kutuphanesi", icon: Files, label: "PDF Kütüphanesi", text: "Çıkmış soru, deneme, not ve resmi metin fişlerini aç." }];

export default function Home() { return <StudyLayout page="home" eyebrow="20 AĞUSTOS · STAJ BAŞLANGIÇ ROTASI" title={<>Bugün defterde <i>akış</i> var.</>}><section className="hero-card"><div className="hero-copy"><div className="hero-chip"><Sparkles size={15} /> 17 günlük seri</div><h2>Bir kayıt, üç kahraman, <br /><span>tek dengeli mizan.</span></h2><p>Defteri sayfa sayfa aç: önce kavramı yakala, sonra işlemi kur, en son sınav turunda kendini dene.</p><Link href="/temel-kavramlar" className="primary-cta">Kavramlarla başla <ArrowRight size={17} /></Link></div><img className="hero-image" src={ASSETS.hero} alt="Açık defter ve denge terazisiyle çalışma masası" /><div className="hero-seal"><Scale size={17} /><span>DENK<br />ÇIKAR</span></div></section><section className="quick-strip" aria-label="Günlük çalışma özeti"><div className="quick-card coral-quick"><span className="quick-icon"><Gamepad2 size={20} /></span><div><strong>Oyun sayfası</strong><small>pratik ayrı yerde</small></div></div><div className="quick-card blue-quick"><span className="quick-icon"><BookMarked size={20} /></span><div><strong>8 sayfa</strong><small>defter sekmesi</small></div></div><div className="quick-card green-quick"><span className="quick-icon"><Trophy size={20} /></span><div><strong>Seviye 04</strong><small>mizan çırağı</small></div></div><Link href="/video-dersleri" className="joke-card"><span>Günün esprisi</span><strong>320 diyor ki: “Malı aldın… benden kaçış yok.”</strong><ArrowRight size={17} /></Link></section><section className="home-index"><div className="home-index-head"><span>ÇALIŞMA SAYFALARIN</span><h2>Bir sayfa, bir görev.</h2><p>Uzun bir akışta kaybolma; ihtiyaç duyduğun defter yaprağını seç.</p></div><div className="destination-grid">{destinations.map((item, index) => { const Icon = item.icon; return <Link key={item.href} href={item.href} className="destination-card"><span className="destination-number">0{index + 1}</span><Icon size={22} /><h3>{item.label}</h3><p>{item.text}</p><b>Sayfayı aç <ArrowRight size={15} /></b></Link>; })}</div></section></StudyLayout>; }
