/* Defter-i Neşeli tasarım notu: Temel kavramlar, ezber kartı yerine rolü olan kısa karakter fişleri ve mikro senaryolarla açıklanır. */
import { useState } from "react";
import { ArrowRight, BookOpenCheck, Check, CircleHelp, Scale, Sparkles } from "lucide-react";
import { SectionHeading } from "./SectionHeading";

const concepts = [
  { code: "V", title: "Varlık", tag: "ELİNDEKİ GÜÇ", color: "blue", line: "Kasa, banka, stok… işletmenin ‘buradayım’ diyen tarafıyım.", rule: "İşletmenin kontrol ettiği ve gelecekte fayda beklediği değerleri anlatır.", example: "Kasa arttıysa 100 Kasa hesabını düşün; varlıklar çoğu kez borç yönünde artar." },
  { code: "B", title: "Borç / Yükümlülük", tag: "SÖZ VERİLEN TARAF", color: "coral", line: "320 kapıda: Malı aldın, ödeme sırası bende.", rule: "İşletmenin dışarıya karşı ödeme veya edim yükümlülüğünü gösterir.", example: "Vadeli alışta satıcıya borç doğar; 320 Satıcılar alacak yönünde çalışır." },
  { code: "Ö", title: "Özkaynak", tag: "SAHİBİN PAYI", color: "purple", line: "Borçlar düştükten sonra kalan hikâye benim.", rule: "Varlıkların, borçlar çıktıktan sonra işletme sahibine kalan finansman payıdır.", example: "Sermaye ve dönem sonucu bu başlıkta birlikte okunur." },
  { code: "G", title: "Gelir", tag: "DÖNEMİN SESİ", color: "green", line: "600 konuşunca satış hikâyesi başlar.", rule: "Dönem içinde ekonomik faydada artış yaratan faaliyet sonuçlarını anlatır.", example: "Kredili satışta 600 Yurtiçi Satışlar çoğunlukla alacak yönünde kaydedilir." },
  { code: "M", title: "Gider", tag: "HİKÂYENİN MALİYETİ", color: "orange", line: "770 der ki: Yönetmek de bir masraf, beni unutma.", rule: "Gelir elde etmek veya faaliyeti sürdürmek için katlanılan tüketim ve harcamalardır.", example: "Yönetim gideri 770’te, pazarlama gideri 760’ta izlenir; ikisi aynı sahne değildir." },
  { code: "T", title: "Tahakkuk Esası", tag: "ÖDEMEYİ BEKLEMEZ", color: "ink", line: "Fatura gelmese de dönem bitti mi, olay kapıya gelir.", rule: "Gelir ve gideri tahsilat/ödeme anından çok ait olduğu dönemde düşünme yaklaşımıdır.", example: "Kullanılan fakat henüz ödenmeyen hizmet, uygun gider ve yükümlülük hesabıyla değerlendirilir." },
  { code: "D", title: "Dönemsellik", tag: "HER ŞEY KENDİ SAYFASINDA", color: "yellow", line: "Bir yılın hikâyesini diğer yılın defterine karıştırma.", rule: "Gelir ve giderler ilgili oldukları hesap dönemine ait gösterilir.", example: "Peşin ödenen uzun süreli gider, tamamı bir anda değil ilgili dönemlere dağıtılarak düşünülür." },
  { code: "K", title: "Belgelendirme", tag: "İZ BIRAK", color: "blue", line: "Belgesiz kayıt, pusulasız yolculuk gibidir.", rule: "Muhasebe kaydının dayandığı işlem belgesini görünür ve izlenebilir tutma ilkesidir.", example: "Fatura, fiş veya makbuz işlem hikâyesinin başlangıç noktasıdır." },
  { code: "S", title: "Sosyal Sorumluluk", tag: "SADECE KÂR DEĞİL", color: "coral", line: "Defter doğruyu yazsın; karar veren de doğruyu görsün.", rule: "Bilginin yalnız işletme için değil, ilgili tüm taraflar için güvenilir üretilmesini vurgular.", example: "Dürüst, tutarlı ve anlaşılır raporlama bu kavramın pratik yüzüdür." },
];

const miniQuestions = [
  { text: "Elektrik kullanıldı; fatura henüz gelmedi. Bu olayı hangi düşünce daha iyi açıklar?", options: ["Tahakkuk esası", "Sadece tahsilat", "Nazım hesap"], correct: 0, note: "Olayın ait olduğu dönemi düşünmek tahakkuk mantığıdır; kayıt örneği işlem ayrıntısına göre kurulmalıdır." },
  { text: "Peşin ödenen bir yıllık sigorta primi neden tek seferde tümüyle gider düşünülmeyebilir?", options: ["Dönemsellik", "Satış geliri", "Mizan dengesi"], correct: 0, note: "Gideri faydalandırdığı dönemlere dağıtma düşüncesi dönemsellik kuralını görünür kılar." },
  { text: "Vadeli mal alışında satıcıya karşı doğan yükümlülük hangi kavram kümesindedir?", options: ["Borç / yükümlülük", "Varlık", "Gelir"], correct: 0, note: "320 Satıcılar, işletmenin satıcıya olan ticari borcunun takip durağıdır." },
];

export function Fundamentals() { const [selected, setSelected] = useState(0); const [questionIndex, setQuestionIndex] = useState(0); const [choice, setChoice] = useState<number | null>(null); const concept = concepts[selected]; const question = miniQuestions[questionIndex]; return <section className="fundamentals"><SectionHeading eyebrow="MUHASEBENİN TEMEL KAVRAMLARI" title="Kavramları ezberleme; rolünü yakala." action={<span className="concept-count"><BookOpenCheck size={14} /> 9 temel durak</span>} /><p className="section-margin-note"><b>Kavram pusulası:</b> Önce olayın ne olduğunu söyle; sonra hangi kavramın sahneye çıktığını seç. Kodlar daha sonra gelir, mantık önce.</p><div className="concept-layout"><div className="concept-list" role="tablist">{concepts.map((item, index) => <button key={item.title} role="tab" aria-selected={selected === index} className={selected === index ? `active ${item.color}` : item.color} onClick={() => setSelected(index)}><b>{item.code}</b><span><small>{item.tag}</small>{item.title}</span><ArrowRight size={14} /></button>)}</div><article className={`concept-detail ${concept.color}`}><div className="concept-seal"><Sparkles size={15} /> {concept.tag}</div><div className="concept-letter">{concept.code}</div><h3>{concept.title}</h3><p className="concept-line">“{concept.line}”</p><div className="concept-rule"><Scale size={18} /><p>{concept.rule}</p></div><div className="concept-example"><span>DEFTER KENARI ÖRNEĞİ</span><p>{concept.example}</p></div></article></div><article className="concept-practice"><div className="practice-copy"><span>3 DAKİKALIK KAVRAM TURU</span><h3>Kuralı yakala, sonra cevabı damgala.</h3><p>{question.text}</p></div><div className="practice-options">{question.options.map((option, index) => { const correct = choice !== null && index === question.correct; const wrong = choice === index && index !== question.correct; return <button key={option} className={`${correct ? "correct" : ""} ${wrong ? "wrong" : ""}`} onClick={() => choice === null && setChoice(index)}><b>{String.fromCharCode(65 + index)}</b>{option}{correct ? <Check size={16} /> : wrong ? <CircleHelp size={16} /> : null}</button>; })}</div>{choice !== null && <div className={`concept-feedback ${choice === question.correct ? "correct" : "wrong"}`}><p><b>{choice === question.correct ? "Doğru kavram yakalandı." : "Yaklaştın; şu ipucuna bak."}</b> {question.note}</p><button onClick={() => { setQuestionIndex((current) => (current + 1) % miniQuestions.length); setChoice(null); }}>Yeni kavram turu <ArrowRight size={14} /></button></div>}</article></section>; }
