/* Defter-i Neşeli tasarım notu: Oyun odası, hızlı soru ve yevmiye fişini aynı çalışma sayfasında; eşleştirmeyi ise ayrı pratik şeridinde tutar. */
import { useState } from "react";
import { ArrowRight, Check, ChevronRight, Gamepad2, Play, Sparkles, X } from "lucide-react";
import { matchPairs, quizQuestions } from "@/data/learningData";
import { SectionHeading } from "./SectionHeading";
import { JournalPractice } from "./JournalPractice";

export function StudyGames({ onAward, onSurprise }: { onAward: (value: number) => void; onSurprise: () => void }) {
  const [quizIndex, setQuizIndex] = useState(0); const [selectedChoice, setSelectedChoice] = useState<string | null>(null); const [quizStatus, setQuizStatus] = useState<"idle" | "correct" | "wrong">("idle"); const [selectedMatch, setSelectedMatch] = useState<string | null>(null); const [matchedCodes, setMatchedCodes] = useState<string[]>([]); const [matchNote, setMatchNote] = useState("Önce bir hesap kodu, sonra doğru tanımı seç.");
  const question = quizQuestions[quizIndex];
  function answerQuestion(code: string) { if (quizStatus !== "idle") return; setSelectedChoice(code); const correct = code === question.correct; setQuizStatus(correct ? "correct" : "wrong"); if (correct) { onAward(12); window.setTimeout(onSurprise, 320); } }
  function nextQuestion() { setQuizIndex((current) => (current + 1) % quizQuestions.length); setSelectedChoice(null); setQuizStatus("idle"); }
  function chooseDefinition(text: string) { if (!selectedMatch) { setMatchNote("Önce soldan bir hesap kodu seç; sonra tanımı eşleştir."); return; } const match = matchPairs.find((pair) => pair.code === selectedMatch); if (match?.text === text) { setMatchedCodes((items) => [...items, selectedMatch]); setMatchNote(`${selectedMatch} doğru yerde. Kural cebine girdi.`); setSelectedMatch(null); onAward(7); } else setMatchNote("Bu eşleşme değil; hesabın hangi işlemden doğduğunu bir daha düşün."); }
  return <section id="oyun-alani" className="game-zone"><SectionHeading eyebrow="OYUN ODASI" title="Eline kalemi al; hamle sende." action={<span className="game-caption"><Play size={14} fill="currentColor" /> Her satırda bir gerekçe</span>} /><div className="game-grid"><article className="quiz-card paper-card"><div className="game-card-top"><span className="game-badge">{question.topic}</span><span className="question-count">0{quizIndex + 1} / 03</span></div><h3>Hızlı tur</h3><p className="question-text">{question.question}</p><div className="answer-list">{question.choices.map((choice) => { const shown = selectedChoice === choice.code; const correct = quizStatus !== "idle" && choice.code === question.correct; const wrong = shown && quizStatus === "wrong"; return <button key={choice.code} className={`answer-option ${shown ? "chosen" : ""} ${correct ? "correct" : ""} ${wrong ? "wrong" : ""}`} onClick={() => answerQuestion(choice.code)}><b>{choice.code}</b><span>{choice.text}</span>{correct ? <Check size={17} /> : wrong ? <X size={17} /> : null}</button>; })}</div>{quizStatus !== "idle" && <div className={`quiz-feedback ${quizStatus}`} aria-live="polite"><strong>{quizStatus === "correct" ? "Tam isabet." : "İpucu zamanı."}</strong><p>{quizStatus === "correct" ? question.explanation : `Yaklaştın. ${question.explanation}`}</p><button onClick={nextQuestion}>Yeni soruya geç <ArrowRight size={15} /></button></div>}</article><JournalPractice onAward={onAward} /></div><article className="match-card"><div className="match-copy"><span className="game-badge pale-badge">EŞLEŞTİRME</span><h3>Hesap kimin hikâyesi?</h3><p>Soldan bir kod, sağdan ona ait olayı seç. Ezber değil, doğuş anını yakala.</p><div className="match-note" aria-live="polite"><Sparkles size={15} /> {matchNote}</div></div><div className="match-board"><div className="match-column">{matchPairs.map((pair) => <button key={pair.code} className={`match-code ${selectedMatch === pair.code ? "selected" : ""} ${matchedCodes.includes(pair.code) ? "done" : ""}`} onClick={() => !matchedCodes.includes(pair.code) && setSelectedMatch(pair.code)}>{matchedCodes.includes(pair.code) ? <Check size={16} /> : null}{pair.code}</button>)}</div><div className="match-column definitions">{matchPairs.map((pair) => <button key={pair.text} className={matchedCodes.includes(pair.code) ? "done" : ""} onClick={() => !matchedCodes.includes(pair.code) && chooseDefinition(pair.text)}>{pair.text}{matchedCodes.includes(pair.code) ? <Check size={16} /> : <ChevronRight size={16} />}</button>)}</div></div></article></section>;
}
